name: Acquire activation files
on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request manual activation files for multiple Unity versions ğŸ”‘
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2020.3.48f1
          - 2021.3.42f1
          - 2022.3.42f1
    steps:
      # GameCI ã® Activation ã‚’åˆ©ç”¨ã—ã¦ alf ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç™ºè¡Œã™ã‚‹
      - name: Request manual activation file for Unity ${{ matrix.unityVersion }}
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ matrix.unityVersion }}

      # ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã®ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ (Unity_v20XX.X.XXXX.alf)
      - name: Expose artifact for Unity ${{ matrix.unityVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: Unity_${{ matrix.unityVersion }}_activation_file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
