name: Acquire multiple activation files
on: 
  pull_request:
    branches:
      - master
jobs:
  activation:
    name: Request activation files for multiple Unity versions ğŸ”‘
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2020.3.48f1
          - 2021.3.42f1
          - 2022.3.42f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Unityã®ã‚¢ã‚¯ãƒ†ã‚£ãƒ™ãƒ¼ã‚·ãƒ§ãƒ³
      - name: Activate Unity ${{ matrix.unityVersion }}
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: ${{ matrix.unityVersion }}  # Matrixã§æŒ‡å®šã—ãŸUnityãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’ä½¿ç”¨
          unityEmail: ${{ secrets.UNITY_EMAIL }}  # Unityã®ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹ã‚’ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆã«è¨­å®š
          unityPassword: ${{ secrets.UNITY_PASSWORD }}  # Unityã®ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã‚’ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆã«è¨­å®š
          unitySerial: ${{ secrets.UNITY_SERIAL }}  # Unityã®ã‚·ãƒªã‚¢ãƒ«ã‚­ãƒ¼ï¼ˆå¿…è¦ãªå ´åˆï¼‰
