name: Acquire multiple activation files
on: 
  pull_request:
    branches:
      - master
jobs:
  activation:
    name: Request activation files for multiple Unity versions ğŸ”‘
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2020.3.48f1
          - 2021.3.42f1
          - 2022.3.42f1
    steps:
      # æ‰‹å‹•ã‚¢ã‚¯ãƒ†ã‚£ãƒ™ãƒ¼ã‚·ãƒ§ãƒ³ãƒ•ã‚¡ã‚¤ãƒ«ã®ãƒªã‚¯ã‚¨ã‚¹ãƒˆ
      - name: Request manual activation file for Unity ${{ matrix.unityVersion }}
        id: getManualLicenseFile
        uses: game-ci/unity-request-manual-activation-file@v4
        with:
          unityVersion: ${{ matrix.unityVersion }}  # Matrixã§æŒ‡å®šã—ãŸUnityãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’ä½¿ç”¨

      # ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã®ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰
      - name: Expose artifact for Unity ${{ matrix.unityVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: Unity_${{ matrix.unityVersion }}_activation_file  # ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã”ã¨ã®ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆå
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}  # ãƒ•ã‚¡ã‚¤ãƒ«ãƒ‘ã‚¹ã‚’ä½¿ç”¨
